# Generated by Django 2.2.2 on 2019-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
