# Generated by Django 2.2.2 on 2019-11-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0005_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
