# Generated by Django 2.2.2 on 2019-11-15 18:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191115_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default.jpeg', upload_to='profile_pics', verbose_name='Profile Photo'),
        ),
    ]
