# Generated by Django 2.2.2 on 2019-10-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0002_auto_20191025_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
