# Generated by Django 2.2.2 on 2019-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0005_auto_20191107_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='lug',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
