# Generated by Django 2.2.2 on 2019-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0006_lug_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
