# Generated by Django 2.2.2 on 2019-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0007_auto_20191107_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
