# Generated by Django 2.2.2 on 2019-11-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0011_auto_20191107_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='slug',
            field=models.SlugField(default='', max_length=128, null=True),
        ),
    ]
