# Generated by Django 2.2.2 on 2019-11-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0014_auto_20191107_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lug',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lug',
            name='province',
        ),
        migrations.AlterField(
            model_name='lug',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
