# Generated by Django 2.2.2 on 2019-11-15 18:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0017_auto_20191115_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(default='lug_default_photo.png', upload_to='lug_cover_images', verbose_name='LUG Cover Image'),
        ),
    ]
