# Generated by Django 2.2.2 on 2019-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0018_auto_20191115_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='lug',
            name='meetup_place',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Meetup Place'),
        ),
        migrations.AlterField(
            model_name='lug',
            name='contact_info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Info'),
        ),
    ]
