# Generated by Django 2.2.2 on 2019-11-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0019_auto_20191122_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lug',
            name='gettogether_page',
        ),
    ]
