# Generated by Django 2.2.2 on 2019-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0021_auto_20191122_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='donate_link',
            field=models.URLField(blank=True, default='#', help_text='Link to page where this LUG accepts donations.', null=True, verbose_name='Donation Page URL'),
        ),
        migrations.AlterField(
            model_name='lug',
            name='facebook',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='lug',
            name='telegram',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='lug',
            name='twitter',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='lug',
            name='website',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='LUG Website'),
        ),
    ]
