# Generated by Django 2.2.2 on 2019-11-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0023_auto_20191123_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='website',
            field=models.URLField(blank=True, default='', null=True, verbose_name='LUG Website'),
        ),
    ]
