# Generated by Django 2.2.2 on 2019-11-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0024_auto_20191123_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='city',
            field=models.ForeignKey(help_text='Use up & down arrows, PageUp/Down keys to quickly find your city', on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='lug',
            name='meetup_place',
            field=models.CharField(blank=True, help_text='Place where LUG members meet (library, restaurant, coffee shop, etc.)', max_length=250, null=True, verbose_name='Meetup Place'),
        ),
        migrations.AlterField(
            model_name='lug',
            name='name',
            field=models.CharField(help_text='The name you choose for the LUG will be used in the permanent link, you can change the name later but the link will remain unchanged.', max_length=100, verbose_name='LUG Name'),
        ),
    ]
