# Generated by Django 2.2.2 on 2019-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0026_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='lug',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lug',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
