# Generated by Django 2.2.2 on 2019-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0027_auto_20191201_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lug',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='lug',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
