# Generated by Django 2.2.2 on 2019-12-01 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lugs', '0028_auto_20191201_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('date', models.DateTimeField()),
                ('summary', models.TextField(verbose_name='Summary')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('lug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugs.Lug')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
