# Generated by Django 2.2.2 on 2019-12-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugs', '0029_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
